version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: pc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patientcare
    ports:
      - "5432:5432"
    volumes:
      - pc_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patientcare"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pc_pgdata:
